# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : ""
title_separator          : "-"
name                     : &name "Sofia Wilson"
description              : &description ""
url                      : "https://sofia-wilson.github.io/"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "sofia-wilson/sofia-wilson.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "headshot.jpg"  
  name             : "Sofia Wilson"
  bio              : "Ph.D. Candidate in Education Policy"
  location         : "Stanford, CA"
  employer         : "Stanford University"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sofia.wilson@stanford.edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sofia-wilson-47343327/"
    - label: "ðŸ¦‹ Bluesky"
      icon: "fab fa-bluesky"   # Bluesky has no native FA icon. Use globe instead.
      url: "https://bsky.app/profile/sofia-wilson.bsky.social"

  
  # Academic websites

