# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Sofia Wilson"
title_separator          : "-"
name                     : &name "Sofia Wilson"
description              : &description ""
url                      : "https://sofia-wilson.github.io/"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "sofia-wilson/sofia-wilson.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Sofia Wilson"
  pronouns         : # example: "she/her"  
  bio              : |
  Ph.D. Candidate  
  Stanford University  
  Graduate School of Education

  location         : "Stanford, CA"
  employer         : ""
  uri              : # URL
  email            : "sofia.wilson@stanford.edu" 

  # Academic websites

